// layout.tsx 
// SPA version 1.0 - 2024 - Amy Mummert - All Rights Reserved
"use client";
import "./globals.css";
import "./page.module.css";
import React, { ReactNode } from 'react';
import Footer from "./Footer";


const Layout = ({ children }: { children: ReactNode }) => {
  if (!children) {
    return null;
  }
  
  return (
    <html lang="en">
      <meta name="description" content="Generated by create next app" />
      <head>
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <meta name="theme-color" content="#000000" />
        <meta
          name="description"
          content="Web site created using create-next-app"/>
        <title>Amy Mummert Portfolio</title>
      </head>
      <body>
        <nav style={{ position: 'fixed', width: '100%', justifyContent: 'center', backgroundColor: '#000', padding: '5px 5px', boxShadow: '0 2px 4px rgba(0, 0, 0, 0.1)' }}>
          <a href="#home" style={{ margin: '0 10px', color: 'white' }}>Home</a>
          <a href="#projects" style={{ margin: '0 10px', color: 'white' }}>Projects</a>
          <a href="#about" style={{ margin: '0 10px', color: 'white'  }}>About</a>
          <a href="#contact" style={{ margin: '0 10px', color: 'white'  }}>Contact</a>
        </nav>   
        <main>
          {children}
        </main>
        <Footer>{children}</Footer>
      </body>
  
   </html>
  );
};

export default Layout;