// layout.tsx 
// SPA version 1.0 - 2024 - Amy Mummert - All Rights Reserved
"use client";
import "./globals.css";
import "./page.module.css";
import React, { ReactNode } from 'react';
import Footer from "./Footer";


const Layout = ({ children }: { children: ReactNode }) => {
  if (!children) {
    return null;
  }
  
  return (
    <html lang="en">
      <meta name="description" content="Generated by create next app" />
      <head>
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <meta name="theme-color" content="#000000" />
        <meta
          name="description"
          content="Web site created using create-next-app"/>
        <title>Amy Mummert Portfolio</title>
      </head>
      <body>
      <nav className="fixed w-full flex justify-right pr-6 bg-black p-1 shadow-md text-2xl font-montserrat">
          <p className="flex w-full pl-8 text-2xl justify-left">Amy Mummert</p>
          <div className="flex">
          <a href="#home" className="mx-2 text-white">Home</a>
          <a href="#projects" className="mx-2 text-white">Projects</a>
          <a href="#about" className="mx-2 text-white">About</a>
          <a href="#contact" className="mx-2 text-white">Contact</a>
          </div>
      </nav>
      <main>
          {children}
      </main>
      <Footer>{children}</Footer>
      </body>

    </html>
  );
};

export default Layout;