
"use client";
import "./globals.css";
import { useState } from 'react';
import VideoPlayer from './VideoPlayer';
import "./page.module.css";

import React, { ReactNode } from 'react';

const Layout = ({ children }: { children: ReactNode }) => {
  const [videoPlayed, setVideoPlayed] = useState(false);

  const handleVideoEnd = () => {
    setVideoPlayed(true);
  };

  return (
    <html>
      <meta name="description" content="Generated by create next app" />
      <head>
        <meta charSet="utf-8" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <meta name="theme-color" content="#000000" />
        <meta
          name="description"
          content="Web site created using create-react-app"
        />
        <title>Amy Mummert Portfolio</title>
        <link rel="icon" href="/favicon.ico" />
        
        </head>
      <body>
        <nav style={{ position: 'fixed', top: 0, width: '100%', backgroundColor: '#fff', padding: '10px 0', boxShadow: '0 2px 4px rgba(0, 0, 0, 0.1)' }}>
          <a href="#home" style={{ margin: '0 15px', color: 'black' }}>Home</a>
          <a href="#projects" style={{ margin: '0 15px', color: 'black' }}>Projects</a>
          <a href="#about" style={{ margin: '0 15px', color: 'black'  }}>About</a>
          <a href="#contact" style={{ margin: '0 15px', color: 'black'  }}>Contact</a>
        </nav>
        <div>
          {videoPlayed ? (
            <h1>Welcome to my portfolio!</h1>
          ) : (
            <VideoPlayer onEnded={handleVideoEnd} />
          )}
        </div>
        <main style={{ marginTop: '60px' }}>
          {children}
        </main>
        <footer style={{ position: 'fixed', bottom: 0, width: '100%', backgroundColor: '#fff', padding: '10px 0', boxShadow: '0 -2px 4px rgba(0, 0, 0, 0.1)' }}>
          <p style={{ margin: 0, textAlign: 'center', color: 'black'}}>© 2021 Amy Mummert</p>
        </footer>
      </body>
    </html>
  );
};

export default Layout;